apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coolapp-devsecops
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/nicc777/learning-kubernetes-basics.git
    targetRevision: kube-ops
    chart: stable/anchore-engine
    helm:
      releaseName: coolapp-anchore-engine
  destination:
    server: https://kubernetes.default.svc
    namespace: devsecops
  syncPolicy:
    automated:
      prune: false 
      selfHeal: false 
