apiVersion: apps/v1
kind: Deployment
metadata:
  name: cool-app-deployment
  labels:
    app: cool-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cool-app
  template:
    metadata:
      labels:
        app: cool-app
    spec:
      containers:
      - name: cool-app
        image: nicc777/cool-app:0.0.1
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: 256Mi
            cpu: 1
          requests:
            memory: 256Mi
            cpu: 500m
        livenessProbe:
          httpGet:
            path: /probe/alive
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /probe/ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: cool-app-service
spec:
  selector:
    app: cool-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer